baseurl = "http://example.org/"
languageCode = "fr"
theme = "prologue"
title = "Maxime Enrietto"
[params]
copyright = "Untitled."
description = "DÃ©velopeur Web Junior"
name = "Maxime E."
[[params.portfolio1]]
alt = ""
source = "img/pic02.jpg"
title = "Ipsum Feugiat"
url = "#"
[[params.portfolio1]]
alt = ""
source = "img/pic03.jpg"
title = "Rhoncus Semper"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic04.jpg"
title = "Magna Nullam"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic05.jpg"
title = "Natoque Vitae"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic06.jpg"
title = "Dolor Penatibus"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic07.jpg"
title = "Orci Convallis"
url = "#"
[[params.social]]
icon = "twitter"
link = "#"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "#"
medium = "facebook"
[[params.social]]
icon = "github"
link = "#"
medium = "github"
[[params.social]]
icon = "dribbble"
link = "#"
medium = "dribbble"
[[params.social]]
icon = "envelope"
link = "#"
medium = "email"
